# File: roles/uwsgi/tasks/configs.yml
---
- name: 'Create uwsgi template'
  template:
    src: "{{ item.value.tmpl_uwsgi | default('lamp') }}.j2"
    dest: "/etc/uwsgi/apps-available/{{ item.key }}.ini"
    backup: Yes
  when: item.value.tmpl_uwsgi is defined
  with_dict: "{{ all_websites }}"
  notify:
    - Reload uwsgi
  tags:
    - uwsgi

- name: 'Create uwsgi symlink'
  file:
    state: "{{ item.value.state | default('link') }}"
    path: "/etc/uwsgi/apps-enabled/{{ item.key }}.ini"
    src: "../apps-available/{{ item.key }}.ini"
  when: item.value.tmpl_uwsgi is defined
  with_dict: "{{ all_websites }}"
  notify:
    - Reload uwsgi
  tags:
    - uwsgi

- name: 'Create uwsgi log directory'
  file:
    state: directory
    path: "/var/log/uwsgi/app/{{ item.key }}"
    owner: "{{ item.value.user }}"
    group: 'adm'
    mode: 0750
  when: item.value.tmpl_uwsgi is defined
  with_dict: "{{ all_websites }}"
  tags:
    - uwsgi
